### ISSUE TITLE
Tagging?

### ISSUE THREAD

**Issue by sbabcock23** [rsnodgrass/pyadtpulse#24]
Hi @rsnodgrass  and @rlippmann,

I know this project is now unsupported but are we tagging the releases going forward? I personally still use this project in relation to my Home Assistant integration.

@rsnodgrass  - I appreciate all the work that went into this project.

**Comment by rsnodgrass** [comment]
Released to PyPi https://pypi.org/project/pyadtpulse/1.0.0/

**Comment by rsnodgrass** [comment]
@sbabcock23 would you try installing hass-adtpulse in HA from main? This is the unreleased update to include pyadtpulse 1.0.0.  I do not have an ADT Pulse system right now to do any testing.

https://github.com/rsnodgrass/hass-adtpulse

**Comment by sbabcock23** [comment]
Perfect thanks @rsnodgrass, thats what I was looking at (the manifest.json file). I would be happy to contribute going forward to hass-adtproject since I have my security system still. I've had some recent challenges and I wanted to dig a bit into it.

**Comment by rsnodgrass** [comment]
@rlippmann Yes, it is a bit confusing. All the methods change if you switch the HA integration to async. Don't feel like you have to do the sync to async change, unless you are having fun!

**Comment by rlippmann** [comment]
@rsnodgrass the async isn’t too bad. The whole platform/config/config flow/update coordinator is confusing. And it doesn’t help that their some of their sample code is inconsistent/unclear.

**Comment by sbabcock23** [comment]
@rlippmann - I will take a look and let you know if there are any changes/issues with either this project or the HA one and attempt to fix it. The config flow is something I have a little bit of experience with as I did create my own integration as well (but has some small issues).

**Comment by rlippmann** [comment]
@sbabcock23 you can also take a look at my person asyncio branch in my forked hass-adtpulse repo. It’s a bit of a mess right now, though. 

I was also looking at, going forward:
1) adding camera. I have 1 of the old adt cameras. I think they use nest now, though
2) only updating partial data instead of updating the entire zone
3) reverse engineering the http calls done by the app. I imagine it doesn’t have all that messy html to decode. This one is going to be a little difficult since I need to proxy the https request with mitm-proxy. Unfortunately, I can’t do it with iOS, and I don’t have an android device. 
4) compute the fingerprint. It downloads some JavaScript to the browser to compute it, but not being a JS/web developer, I’m not exactly sure what it’s doing
